baseURL = "/tutorial"
languageCode = "en-us"
title = "Ventilator Managment Tutorial"
author = "Sami Safadi"
theme = "hugo-theme-learn"
publishDir = "tutorial"
[outputs]
home = [ "HTML", "RSS", "JSON"]