baseURL = "/book"
languageCode = "en-us"
title = "Interactive Book on Ventilator Managment"
author = "Sami Safadi"
theme = "hugo-theme-learn"
publishDir = "book"
[outputs]
home = [ "HTML", "RSS", "JSON"]